### ISSUE TITLE
[Feature] Data caching

### ISSUE THREAD

**Issue by cirex-web** [ScottyLabs/dining-api#152]
### Description

I was told that any web scraping/processing failure would trigger a complete data wipe, which is probably not good.

**Comment by cirex-web** [comment]
ig the thing might've not errored out and instead returned an empty object? I don't know the details of the incident (did the entire server crash or something?), so just a guess

**Comment by GhostOf0days** [comment]
Yeah it was an empty object caused by CMU website being broken, so dining API unable to get data and caching the broken stat.
