### ISSUE TITLE
[Bug] Incorrect Menus for Locations that Often Change Menus

### ISSUE THREAD

**Issue by GhostOf0days** [ScottyLabs/dining-api#28]
There’s an issue with rotating menus on CMUEats: for places that change menus often, like Innovation Kitchen, CMUEats often has the incorrect menu. This could be caused because the API caches the menus for too long. If this is so, it can be fixed by adjusting the duration of the cache.

**Comment by ScottyLabsDeploy** [comment]
How long does it take presently for the cache to get stale?

**Comment by 0dayReaper** [comment]
Someone else said their friend experienced this bug in #tech-cmueats 3 months ago. I'm unsure how out of date those locations are.

**Comment by Nicolapps** [comment]
The cache’s TTL is 6 hours: https://github.com/ScottyLabs/dining-api/blob/a7c6cbef685d287687644c864a4da70daddf8b56/src/server.ts#L86

Shortening it could solve the issue
