### ISSUE TITLE
[Bug] All locations are placed in the bottom-right corner of the map

### ISSUE THREAD

**Issue by Nicolapps** [ScottyLabs/dining-api#46]
It looks like the dining website places all dining locations in the bottom right corner of the map. This results in CMU Map showing wrong locations for all restaurants that we didn’t fix manually.

<img width="1129" alt="image" src="https://github.com/ScottyLabs/cmueats/assets/7029582/ecdf22f4-4eef-4ba1-b56a-052ce9ee4a44">

**Comment by GhostOf0days** [comment]
From the locations we currently parse, the non-overwritten locations are:
1. Hunan Express - Newell-Simon Atrium
2. Entropy+ - Cohon Center, Ground Floor
3. Au Bon Pain At Skibo Café - Cohon Center, Second floor
4. El Gallo De Oro - Cohon Center, Ground Floor
5. Food Hall At Resnik - Resnik House
6. Stephanie's - Market C - Mellon Institute, Fourth Floor, Room 401
7. The Exchange - Posner Hall, 1st Floor
8. La Prima Espresso - Wean Hall, 5th Floor
9. Millie's Coffee 'N' Creamery - Rohr Commons, Tepper Building, Second floor
10. Nourish - Cohon Center, Second floor
11. Schatz Dining Room - Cohon Center, Second floor
12. Revolution Noodle - Cohon Center, 2nd Floor, Marketplace
13. Build Pizza - Rohr Commons, Tepper Building, 2nd Floor
14. Burger 412 - Rohr Commons, Tepper Building, 2nd Floor
15. De Fer Coffee & Tea At Maggie Murph Café - Hunt Library, Rothberg's Roasters
16. Rohr Café - La Prima, Gates Hillman Centers, Third floor
17. Pom And Honey - Rohr Commons, Tepper Building, 2nd Floor
18. Wild Blue Sushi - Ruge Atrium

**Comment by GhostOf0days** [comment]
From the locations we currently parse, the non-overwritten locations are:
1. Hunan Express
2. Entropy+
3. Au Bon Pain At Skibo Café
4. El Gallo De Oro
5. Food Hall At Resnik
6. Stephanie's - Market C
7. The Exchange
8. La Prima Espresso
9. Millie's Coffee 'N' Creamery - Rohr Commons
10. Nourish
11. Schatz Dining Room
12. Revolution Noodle
13. Build Pizza - Rohr Commons
14. Burger 412 - Rohr Commons
15. De Fer Coffee & Tea At Maggie Murph Café
16. Rohr Café - La Prima
17. Pom And Honey - Rohr Commons
18. Wild Blue Sushi - Ruge Atrium

**Comment by GhostOf0days** [comment]
Tested for parser issue. This is not an issue on our side. It's CMU like always. 😭

**Comment by GhostOf0days** [comment]
Probably will have to add location overwrites for every single location. They still haven't fixed the menus they displayed, so we get 403 or 404 errors for all of them on CMUEats. 😭

**Comment by GhostOf0days** [comment]
We should wait until CMU fixes their dining website as the menus are also undergoing rennovations then overwrite every single location to future proof it.

**Comment by GhostOf0days** [comment]
forgot to close
